# Generated by Django 3.2.6 on 2021-11-03 21:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('urlalias', '0003_testurlalias'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitas_ind',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ip', models.TextField(unique=True)),
                ('alias', models.TextField()),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
