# Generated by Django 3.2.6 on 2021-11-03 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlalias', '0004_visitas_ind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitas_ind',
            name='ip',
            field=models.TextField(),
        ),
    ]
